.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large
  image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - quality
  - deploy
  - merge
  - release

compile:
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - mvn -U compile
  except:
    - master

quality_check:
  stage: quality
  <<: *default
  <<: *default_tag
  when: manual
  before_script:
    - export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
  script:
    - mvn clean install -U -Pquality_check -Dproject.version='CI-TEST-${CI_JOB_ID}-SNAPSHOT' -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - cat dropwizard-db-sharding-bundle/target/site/jacoco/index.html
  artifacts:
    reports:
      junit:
        - dropwizard-db-sharding-bundle/target/surefire-reports/TEST-*.xml

deploy_artifacts:
  stage: deploy
  <<: *default
  <<: *default_tag
  when: manual
  allow_failure: true
  script:
    - mvn clean deploy -U -DskipTests
  except:
    - master
    - develop

stage_merge_status:
  stage: merge
  <<: *default
  <<: *default_tag
  allow_failure: false
  script:
    - git fetch
    - git merge-base --is-ancestor $CI_COMMIT_SHA origin/stage
  only:
    - merge_requests
  except:
    - master
    - develop

release_library:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull
    - git checkout develop
    - git pull
    - mvn -U jgitflow:release-start jgitflow:release-finish -DgenerateChangelog
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop
